#Ubuntu Image
FROM ubuntu:latest
LABEL org.opencontainers.image.source = "https://github.com/GoingOffRoading/GlusterFS"

# Install Gluster + dependancies 
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:gluster/glusterfs-9 && \
    apt-get update && \
    apt-get install -y glusterfs-server

# Start the Docker daemon
CMD glusterd -N
