# Gluster v9.x 
# Ubuntu image instead of Alpine for install simplicty of Launchpad: https://launchpad.net/~gluster/+archive/ubuntu/glusterfs-9

FROM ubuntu:latest
LABEL org.opencontainers.image.source=https://github.com/goingoffroading/glusterfs

# Install Gluster + dependancies 
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:gluster/glusterfs-9 && \
    apt-get update && \
    apt-get install -y glusterfs-server

#CMD ["/usr/sbin/init"]
CMD glusterd -N


#COPY /gluster-entrypoint.sh /
#RUN chmod +x /gluster-entrypoint.sh

#ENTRYPOINT [ "/bin/bash", "/gluster-entrypoint.sh" ]
#RUN glusterd --version

#CMD service glusterd start 